=== ZentoDev/bytecourier3000/dati/xml-xsd/crediti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="richieste">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="richiesta_crediti" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="richiesta_crediti">
    <xs:complexType>
        <xs:attribute name="id_richiesta" type="xs:string" use="required"/>
        <xs:attribute name="username" type="xs:string" use="required"/>
        <xs:attribute name="crediti" type="xs:float" use="required" />
        <xs:attribute name="stato" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="accettata"/>
                    <xs:enumeration value="rifiutata"/>
                    <xs:enumeration value="in_attesa"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:element>

</xs:schema>

=== ZentoDev/bytecourier3000/dati/xml/crediti.xml
<?xml version="1.0" encoding="UTF-8"?>
<richieste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="crediti.xsd">
    <richiesta_crediti id_richiesta="0" username="marco" crediti="25" stato="accettata" />
    <richiesta_crediti id_richiesta="1" username="stella" crediti="457" stato="rifiutata" />
    <richiesta_crediti id_richiesta="2" username="simona" crediti="14" stato="in_attesa" />
    <richiesta_crediti id_richiesta="3" username="marcolino71" crediti="7" stato="in_attesa" />
    <richiesta_crediti id_richiesta="4" username="marcolino71" crediti="8" stato="accettata" />
    <richiesta_crediti id_richiesta="5" username="marcolino71" crediti="48" stato="in_attesa" />
    <richiesta_crediti id_richiesta="6" username="marcolino71" crediti="10" stato="in_attesa" />
</richieste>
