=== ZentoDev/bytecourier3000/dati/xml/mock/interventi.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="lista_interventi">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="intervento" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="intervento">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="testo" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="valutazione_utente" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="id_intervento" type="xs:string" use="required" />
            <xs:attribute name="id_risposta" type="xs:string" use="required" />
            <xs:attribute name="username" type="xs:string" use="required" />
            <xs:attribute name="admin" type="xs:boolean" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="valutazione_utente">
        <xs:complexType>
            <xs:attribute name="id_user" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ZentoDev/bytecourier3000/dati/xml/interventi.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_interventi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="interventi.xsd">
    <intervento id_intervento="1" id_risposta="" username="stella" admin="false">
        <testo>Dove si possono trovare info sulle spedizioni?</testo>
    </intervento>
    <intervento id_intervento="2" id_risposta="1" username="marco" admin="false">
        <testo>sezione informazioni!</testo>
        <valutazione_utente id_user="marcolino71" />
        <valutazione_utente id_user="stella" />
    </intervento>
    <intervento id_intervento="3" id_risposta="" username="marco" admin="false">
        <testo>Ciao a tutti!</testo>
    </intervento>
    <intervento id_intervento="4" id_risposta="" username="marco" admin="false">
        <testo>Dove posso richiedere i crediti?</testo>
    </intervento>
    <intervento id_intervento="5" id_risposta="4" username="marco" admin="false">
        <testo>Vedi bene nella sezione richiedicrediti</testo>
    </intervento>
    <intervento id_intervento="6" id_risposta="1" username="marcolino71" admin="false">
        <testo>Guarda nella sezione"informazioni" che si trova qui sulla sinistra. </testo>
        <valutazione_utente id_user="marcolino71" />
    </intervento>
    <intervento id_intervento="7" id_risposta="1" username="marcolino71" admin="false">
        <testo>La barra a sinistra dovepuoi fare anche il Logout</testo>
    </intervento>
    <intervento id_intervento="8" id_risposta="" username="marcolino71" admin="false">
        <testo>Posso visualizzare lo storico degli ordini?</testo>
    </intervento>
    <intervento id_intervento="9" id_risposta="" username="admin" admin="true">
        <testo>Come accedo al sito?</testo>
    </intervento>
    <intervento id_intervento="10" id_risposta="9" username="admin" admin="true">
        <testo>Ãˆ sufficiente inserire le proprie credenziali nella sezione di login. </testo>
    </intervento>
    <intervento id_intervento="11" id_risposta="8" username="marcolino71" admin="false">
        <testo>Basta cercare "storico ordini" nel menu di fianco a sinistra.</testo>
    </intervento>
</lista_interventi>
