=== ZentoDev/bytecourier3000/dati/xml/mock/operazioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="lista_operazioni">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="operazione" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="operazione">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="note" />
        </xs:sequence>
        <xs:attribute name="id_operazione" type="xs:string" use="required" />
        <xs:attribute name="username_bytecourier" type="xs:string" use="required" />
        <xs:attribute name="id_ordine" type="xs:string" use="required" />
        <xs:attribute name="stato" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="1"></xs:enumeration> <!--transito verso cliente per ritiro-->
                    <xs:enumeration value="2"></xs:enumeration> <!--pacco ritirato-->
                    <xs:enumeration value="3"></xs:enumeration> <!--pacco al centro byte courier-->
                    <xs:enumeration value="4"></xs:enumeration> <!--transito verso destinatario-->
                    <xs:enumeration value="5"></xs:enumeration> <!--consegna effettuata-->
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="problema" type="xs:boolean" />
    </xs:complexType>
</xs:element>

<xs:element name="note">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nota" maxOccurs="unbounded" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="nota">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="data_nota" type="xs:dateTime" use="required" />
                <xs:attribute name="username" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

</xs:schema>

=== ZentoDev/bytecourier3000/dati/xml/operazioni.xml
<?xml version="1.0" encoding="UTF-8"?>

<lista_operazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="operazioni.xsd">

<operazione id_operazione="1" username_bytecourier="" id_ordine="1" stato="1">
    <note></note>
</operazione>

<operazione id_operazione="2" username_bytecourier="Wick64" id_ordine="2" stato="4">
    <note>
        <nota data_nota="2022-09-14T09:30:00" username="Wick64">
            Il ritiro Ã¨ proceduto secondo i piani
        </nota>
    </note>
</operazione>

<operazione id_operazione="3" username_bytecourier="" id_ordine="3" stato="2">
    <note></note>
</operazione>

<operazione id_operazione="4" username_bytecourier="" id_ordine="4" stato="3">
    <note></note>
</operazione>

<operazione id_operazione="5" username_bytecourier="" id_ordine="5" stato="1">
    <note></note>
</operazione>

<operazione id_operazione="6" username_bytecourier="Wick64" id_ordine="6" stato="5">
    <note></note>
</operazione>

<operazione id_operazione="7" username_bytecourier="Wick64" id_ordine="7" stato="1">
    <note></note>
</operazione>

</lista_operazioni>
